// lib/sendEmailWithAttachment.js
require('dotenv').config();
const nodemailer = require('nodemailer');
const fs = require('fs');

const required = ['SMTP_USER', 'SMTP_PASS', 'SMTP_TO', 'SMTP_NAME'];
const missing = required.filter(k => !process.env[k]);
if (missing.length) {
  throw new Error('Missing required .env keys: ' + missing.join(', '));
}

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

function sendEmailWithAttachment(filePath) {
  return new Promise((resolve, reject) => {
    // Check file exists
    if (!fs.existsSync(filePath)) {
      return reject(new Error(`File not found: ${filePath}`));
    }

    const mailOptions = {
      from: `"${process.env.SMTP_NAME}" <${process.env.SMTP_USER}>`,
      to: process.env.SMTP_TO,
      subject: '📎 Report from Yellow Haven App',
      text: 'Attached is the PDF report generated by the app.',
      attachments: [
        {
          filename: filePath.split(/[\/\\]/).pop(),
          path: filePath,
        },
      ],
    };

    transporter.sendMail(mailOptions, (err, info) => {
      if (err) return reject(err);
      resolve(info);
    });
  });
}

module.exports = { sendEmailWithAttachment };
